# Generated by Django 5.2.4 on 2025-08-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
    ]
