# Generated by Django 5.2.4 on 2025-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0003_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting', max_length=254, verbose_name='Image Name')),
                ('description', models.TextField(blank=True, default='', help_text='This is variable of the setting', verbose_name='Image Description')),
                ('image_file', models.ImageField(default='', help_text='Upload an image file', upload_to='images/', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ['name'],
            },
        ),
    ]
