# Generated by Django 5.2.4 on 2025-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0004_imagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Enter the order of the social media link', verbose_name='Order')),
                ('link', models.URLField(blank=True, default='', help_text='Enter the URL of your social media profile', verbose_name='Link')),
                ('icon', models.CharField(blank=True, default='', help_text='Enter the icon class for your social media profile', max_length=100, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ['order'],
            },
        ),
    ]
