# Generated by Django 5.2.4 on 2025-08-15 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0005_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('school_name', models.CharField(blank=True, help_text='Enter the name of the institution', max_length=100, verbose_name='Institution Name')),
                ('department', models.CharField(blank=True, help_text='Enter your department', max_length=254, verbose_name='Department')),
                ('position', models.CharField(blank=True, help_text='Enter your position', max_length=100, verbose_name='Position')),
                ('start_date', models.DateField(blank=True, help_text='Enter the start date of your education', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Enter the end date of your education', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('company_name', models.CharField(blank=True, help_text='Enter the name of the company', max_length=100, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, help_text='Enter your job title', max_length=100, verbose_name='Job Title')),
                ('position', models.CharField(blank=True, help_text='Enter your position', max_length=100, verbose_name='Position')),
                ('start_date', models.DateField(blank=True, help_text='Enter the start date of your experience', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Enter the end date of your experience', null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('order', models.IntegerField(blank=True, default=0, help_text='This is variable of the setting', verbose_name='Skill Order')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting', max_length=100, verbose_name='Skill Name')),
                ('percentage', models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Skill Percentage')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order'],
            },
        ),
    ]
