# Generated by Django 5.2.4 on 2025-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0008_customeroffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=True, default='', help_text='Enter the name of the site', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='A short description about the site.', help_text='Enter a short description about the site', max_length=254, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Customer Testimonial',
                'verbose_name_plural': 'Customer Testimonials',
                'ordering': ['-created_date'],
            },
        ),
    ]
