# Generated by Django 5.2.4 on 2025-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv', '0009_customertestimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilterSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Enter the order of the Data Filter Slug', verbose_name='Order')),
                ('slug', models.SlugField(blank=True, default='', help_text='Enter the slug for the Data Filter Slug', max_length=100, verbose_name='Data Filter Slug')),
                ('image_file', models.ImageField(default='', help_text='Upload an image file', upload_to='images/', verbose_name='Image File')),
            ],
            options={
                'verbose_name': 'Data Filter',
                'verbose_name_plural': 'Data Filters',
                'ordering': ['order'],
            },
        ),
    ]
